package com.example.bekirc.minigolfapp.data.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.bekirc.minigolfapp.data.db.entity.Game;
import com.example.bekirc.minigolfapp.data.db.entity.Player;

import com.example.bekirc.minigolfapp.data.db.dao.GameDao;
import com.example.bekirc.minigolfapp.data.db.dao.PlayerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameDaoConfig;
    private final DaoConfig playerDaoConfig;

    private final GameDao gameDao;
    private final PlayerDao playerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameDaoConfig = daoConfigMap.get(GameDao.class).clone();
        gameDaoConfig.initIdentityScope(type);

        playerDaoConfig = daoConfigMap.get(PlayerDao.class).clone();
        playerDaoConfig.initIdentityScope(type);

        gameDao = new GameDao(gameDaoConfig, this);
        playerDao = new PlayerDao(playerDaoConfig, this);

        registerDao(Game.class, gameDao);
        registerDao(Player.class, playerDao);
    }
    
    public void clear() {
        gameDaoConfig.getIdentityScope().clear();
        playerDaoConfig.getIdentityScope().clear();
    }

    public GameDao getGameDao() {
        return gameDao;
    }

    public PlayerDao getPlayerDao() {
        return playerDao;
    }

}
