package com.example.bekirc.minigolfapp.data.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PLAYER.
 */
public class Player {

    /** Not-null value. */
    private String name;
    private String scoreList;
    private Integer totalScore;
    private Integer totalTurnNumber;
    private String date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Player() {
    }

    public Player(String name, String scoreList, Integer totalScore, Integer totalTurnNumber, String date) {
        this.name = name;
        this.scoreList = scoreList;
        this.totalScore = totalScore;
        this.totalTurnNumber = totalTurnNumber;
        this.date = date;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getScoreList() {
        return scoreList;
    }

    public void setScoreList(String scoreList) {
        this.scoreList = scoreList;
    }

    public Integer getTotalScore() {
        return totalScore;
    }

    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    public Integer getTotalTurnNumber() {
        return totalTurnNumber;
    }

    public void setTotalTurnNumber(Integer totalTurnNumber) {
        this.totalTurnNumber = totalTurnNumber;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    public void setScoreListByTurnNumber(int score, int turnNumber){

    }

    public int getScoreListByTurnNumber(){
        return 0;
    }
    // KEEP METHODS END

}
